"""Pan/tilt servos, driven from the tracking error.

Optional -- everything else works without it. Enable with ``--turret``. On a
machine with no PWM hardware it falls back to a simulation backend so the rest
of the program still runs and can be tested.

The control law
---------------
The camera is bolted to the mount, so it moves with it. That makes the measured
angle to the person *exactly* the correction the mount needs -- there is no
coordinate transform to do. So the loop is simply:

    command += gain * error * dt

Each tick moves a fraction of the way to the target, so the error decays
geometrically.

The ``* dt`` matters more than it looks. The obvious version applies the gain
once per *frame*, which makes the real loop gain "gain x frame rate" -- so
swapping to a lighter model, or plugging in a faster camera, silently makes the
mount more aggressive until it oscillates, and a slower one makes it sluggish.
Multiplying by the frame interval instead means ``gain`` is in units of
"fraction of the error corrected per second" and the behaviour is the same at
15 fps or 30. That is why the numbers below are around 5 rather than around 0.2.

The ceiling is latency, not gain: detection takes ~30 ms, so the mount is always
acting on slightly stale information, and above roughly 8 per second it starts
overshooting and hunting.
"""
from __future__ import annotations

import glob
import os
import re
import time
from dataclasses import dataclass


# ---------------------------------------------------------------------------
# Calibration. These describe this particular build and were measured on it.
# ---------------------------------------------------------------------------
@dataclass
class Axis:
    channel: int          # hardware PWM channel
    gpio: int             # which pin that channel comes out on (for the banner)
    min_deg: float        # travel limits; never exceeded
    max_deg: float
    gain: float           # error corrected per second (see the module docstring)
    trim_deg: float = 0.0  # corrects the horn not sitting square on the spline
    invert: bool = False   # servo mounted facing the other way
    span_deg: float = 180.0        # the servo's full mechanical sweep
    min_pulse_us: float = 500.0
    max_pulse_us: float = 2500.0
    dead_deg: float = 0.35         # below this, hold still instead of buzzing


# Tuned on the real mount. Pan is the faster axis; tilt is kept a little calmer
# because it carries the camera against gravity and shows overshoot sooner.
PAN = Axis(channel=1, gpio=13, min_deg=-90.0, max_deg=90.0,
           gain=6.0, trim_deg=0.38, invert=True)
TILT = Axis(channel=0, gpio=12, min_deg=-30.0, max_deg=30.0,
            gain=4.0, trim_deg=9.73, invert=True)

MAX_DT = 0.2              # a stalled frame must not turn into one huge jump


@dataclass
class Scan:
    """What the mount does when it cannot see anybody.

    Holding still is right for a moment -- people step behind things and come
    back -- but a mount that never looks around will never find anyone again
    once they leave. So: hold briefly, then sweep the pan axis slowly across its
    travel with the tilt parked level, and drop straight back into tracking the
    instant somebody appears.
    """
    enabled: bool = True
    after_s: float = 2.0       # hold this long before starting to look around
    rate_deg_s: float = 12.0   # sweep speed; 180 deg takes 15 s at 12 deg/s
    dwell_s: float = 0.8       # pause at each end rather than slamming round
    tilt_deg: float = 0.0      # where tilt parks while sweeping

FRAME_HZ = 250.0          # digital servos accept far more than the usual 50 Hz,
                          # and a faster frame means a command arrives sooner


# ---------------------------------------------------------------------------
# PWM output
# ---------------------------------------------------------------------------
class HardwarePWM:
    """Kernel PWM through sysfs. Jitter-free, because the pulse is generated by
    a peripheral rather than by Python."""

    name = "hardware PWM"

    def __init__(self, frame_hz: float = FRAME_HZ):
        self.period_ns = int(round(1e9 / frame_hz))
        self.chip = self._find_chip()
        if self.chip is None:
            raise RuntimeError(
                "no usable PWM chip. Add this line to /boot/firmware/config.txt "
                "and reboot:\n    dtoverlay=pwm-2chan,pin=12,func=4,pin2=13,func2=4")
        self._exported: set = set()

    @staticmethod
    def _find_chip():
        """Pick the PWM chip actually wired to GPIO12/13.

        Taking the first chip with two channels is wrong on a Pi 5: the
        numbering is neither sequential nor stable across kernels, and one of
        the RP1 channels drives the CPU cooling fan. Claiming that one would
        fight thermal management, so it is excluded explicitly.
        """
        for path in sorted(glob.glob("/sys/class/pwm/pwmchip*")):
            try:
                with open(os.path.join(path, "npwm")) as fh:
                    if int(fh.read().strip()) < 2:
                        continue
            except (OSError, ValueError):
                continue
            if glob.glob(os.path.join(path, "device", "consumer:platform:cooling_fan*")):
                continue                       # that one is the fan
            device = os.path.realpath(os.path.join(path, "device")).lower()
            # On a Pi 5 the RP1 block sits behind PCIe and the string "rp1"
            # never appears in the path, so match its address instead.
            if "rp1" in device or re.search(r"/1f000[0-9a-f]+\.pwm$", device):
                return path
        return None

    @staticmethod
    def _wait_writable(path: str, timeout: float = 3.0) -> None:
        """Wait until a freshly exported sysfs file can actually be written.

        Exporting a channel creates its files owned by root, and udev then
        applies the gpio group ownership *asynchronously*. Checking only that
        the file exists wins the race about half the time -- measured on this
        Pi, channel 0 succeeded and channel 1 raised PermissionError on the very
        next line.
        """
        deadline = time.time() + timeout
        while time.time() < deadline:
            if os.path.exists(path) and os.access(path, os.W_OK):
                return
            time.sleep(0.01)
        raise RuntimeError(
            "%s is not writable. Check you are in the 'gpio' group (run 'id'); "
            "you must log out and back in after being added." % path)

    def _write(self, path: str, value) -> None:
        with open(path, "w") as fh:
            fh.write(str(value))

    def _ensure(self, channel: int) -> str:
        base = os.path.join(self.chip, "pwm%d" % channel)
        if channel not in self._exported:
            if not os.path.exists(base):
                self._write(os.path.join(self.chip, "export"), channel)
            self._wait_writable(os.path.join(base, "period"))
            self._write(os.path.join(base, "period"), self.period_ns)
            self._write(os.path.join(base, "duty_cycle"), 0)
            self._write(os.path.join(base, "enable"), 1)
            self._exported.add(channel)
        return base

    def set_pulse_us(self, channel: int, microseconds: float) -> None:
        base = self._ensure(channel)
        duty_ns = int(max(0.0, microseconds) * 1000)
        self._write(os.path.join(base, "duty_cycle"), min(duty_ns, self.period_ns))

    def close(self) -> None:
        for channel in list(self._exported):
            base = os.path.join(self.chip, "pwm%d" % channel)
            try:
                # Stop driving before releasing, so the servo is not left
                # holding a stale pulse and buzzing against it.
                self._write(os.path.join(base, "duty_cycle"), 0)
                self._write(os.path.join(base, "enable"), 0)
                self._write(os.path.join(self.chip, "unexport"), channel)
            except OSError:
                pass
        self._exported.clear()


class SimulatedPWM:
    """Records pulses instead of sending them, so this runs anywhere."""

    name = "simulated (no PWM hardware)"

    def __init__(self, frame_hz: float = FRAME_HZ):
        self.pulses: dict = {}

    def set_pulse_us(self, channel: int, microseconds: float) -> None:
        self.pulses[channel] = microseconds

    def close(self) -> None:
        pass


def make_backend(kind: str = "auto"):
    if kind == "sim":
        return SimulatedPWM()
    try:
        return HardwarePWM()
    except Exception as exc:
        if kind == "hardware":
            raise
        print("  [turret] no PWM hardware (%s) -- simulating." % exc)
        return SimulatedPWM()


# ---------------------------------------------------------------------------
# The mount
# ---------------------------------------------------------------------------
class Turret:
    """Two servos, each closing the loop on its own axis."""

    def __init__(self, backend=None, pan: Axis = PAN, tilt: Axis = TILT,
                 scan: Scan | None = None):
        self.backend = backend if backend is not None else make_backend()
        self.pan, self.tilt = pan, tilt
        self.scan = scan if scan is not None else Scan()
        self.pan_deg = 0.0          # where we have commanded each axis to be
        self.tilt_deg = 0.0
        self.at_limit = False
        self.scanning = False
        self._last_seen = time.perf_counter()
        self._sweep_dir = 1         # +1 sweeping right, -1 sweeping left
        self._dwell_until = 0.0
        self.center()

    def _write(self, axis: Axis, degrees: float) -> float:
        """Clamp to the travel limits and send the matching pulse."""
        degrees = max(axis.min_deg, min(axis.max_deg, degrees))
        d = (-degrees if axis.invert else degrees) + axis.trim_deg
        fraction = min(1.0, max(0.0, 0.5 + d / axis.span_deg))
        self.backend.set_pulse_us(
            axis.channel,
            axis.min_pulse_us + fraction * (axis.max_pulse_us - axis.min_pulse_us))
        return degrees

    def center(self) -> None:
        self.pan_deg = self._write(self.pan, 0.0)
        self.tilt_deg = self._write(self.tilt, 0.0)

    def update(self, yaw: float | None, pitch: float | None, dt: float) -> None:
        """One control tick. Angles are the offsets reported by the tracker.

        Because the camera moves with the mount, the error and the correction
        are the same quantity -- so the yaw error is simply added to the pan
        command, scaled by the gain and the time since the last tick.
        """
        dt = max(0.0, min(dt, MAX_DT))
        now = time.perf_counter()

        if yaw is None or pitch is None:
            self._search(now, dt)
            return

        self._last_seen = now
        self.scanning = False
        before = (self.pan_deg, self.tilt_deg)
        if abs(yaw) > self.pan.dead_deg:
            self.pan_deg = self._write(
                self.pan, self.pan_deg + self.pan.gain * yaw * dt)
        if abs(pitch) > self.tilt.dead_deg:
            self.tilt_deg = self._write(
                self.tilt, self.tilt_deg + self.tilt.gain * pitch * dt)

        # "At a stop and still being asked to go further" -- worth showing on the
        # HUD, because the mount then simply cannot reduce the error any more.
        self.at_limit = (
            (self.pan_deg in (self.pan.min_deg, self.pan.max_deg)
             and self.pan_deg == before[0] and abs(yaw) > self.pan.dead_deg)
            or (self.tilt_deg in (self.tilt.min_deg, self.tilt.max_deg)
                and self.tilt_deg == before[1] and abs(pitch) > self.tilt.dead_deg))

    def _search(self, now: float, dt: float) -> None:
        """Nobody in frame: hold for a moment, then sweep looking for someone."""
        if not self.scan.enabled or now - self._last_seen < self.scan.after_s:
            self.scanning = False
            return                              # they may just have stepped away

        self.scanning = True
        self.tilt_deg = self._write(self.tilt, self.scan.tilt_deg)  # park level

        if now < self._dwell_until:
            return                              # pausing at the end of a sweep

        nxt = self.pan_deg + self._sweep_dir * self.scan.rate_deg_s * dt
        if nxt >= self.pan.max_deg:
            nxt, self._sweep_dir = self.pan.max_deg, -1
            self._dwell_until = now + self.scan.dwell_s
        elif nxt <= self.pan.min_deg:
            nxt, self._sweep_dir = self.pan.min_deg, 1
            self._dwell_until = now + self.scan.dwell_s
        self.pan_deg = self._write(self.pan, nxt)

    def release(self) -> None:
        """Stop driving the servos so they go limp instead of buzzing."""
        for axis in (self.pan, self.tilt):
            self.backend.set_pulse_us(axis.channel, 0)

    def close(self) -> None:
        try:
            self.release()
        finally:
            self.backend.close()
